networks:
  net:
    driver: bridge

services:
  jellyfin:
    image: docker.io/jellyfin/jellyfin:latest 
    container_name: jellyfin
    restart: unless-stopped
    labels:
      - 'io.containers.autoupdate=registry'
    ports:
      - 8096:8096
    volumes:
      - ./jellyfin/config:/config:z
      - $HOME/.cache/jellyfin:/cache:z
      - $HOME/Videos:/media:z

