networks:
  net:
    driver: bridge

services:
  jellyfin:
    image: docker.io/jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - 8096:8096
    volumes:
      - $HOME/.config/jellyfin:/config:z
      - $HOME/.cache/jellyfin:/cache:z
      - /mnt/bulk/music:/music:z
      - /mnt/bulk/movies:/movies:z
      - /mnt/bulk/shows:/shows:z
